### ISSUE TITLE
Openssl issue.

### ISSUE THREAD

**Issue by ImmRanneft** [mbround18/ark-manager-web#10]
Can't run the server cause openssl issue
```
/opt/ark-manager-web/vendor/ruby-2.3.1/lib/ruby/2.3.0/openssl.rb:13:in `require': /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /opt/ark-manager-web/vendor/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/openssl.so)
```

debian jessie

``openssl version`` gives me ``OpenSSL 1.1.0e  16 Feb 2017``

**Comment by mbround18** [comment]
Thank you @ImmRanneft ill look into this

**Comment by ImmRanneft** [comment]
@mbround18 you are welcome :) I'm really appreciated that this tool exists and I don't need to play around ``ark-server-tools``

**Comment by mbround18** [comment]
Im glad, my goal was to make using ark-server-tools even easier :P since im done moving expect some new features and bug fixes to be coming down the pipe soon :) what step on the read me did you fail on? I was able to install the full stack and run successfully on debian jessie. Did you install all the dependencies?

**Comment by ImmRanneft** [comment]
@mbround18 for your info - this may be related http://stackoverflow.com/questions/15907103/ruby-not-finding-new-version-of-openssl

The guy says that each time openssl is updated ruby`s open ssl should be recompiled too.

**Comment by ImmRanneft** [comment]
@mbround18 I failed on step ``ark-manager-web run interface`` twice - first time with TZ (added to env_config.json). Then with openssl issue.

**Comment by ImmRanneft** [comment]
@mbround18 Also for your info - I was doing automatical installation via packaged installation

**Comment by mbround18** [comment]
Ahh I see, if you install using the readme on debian jessie it will work fine but from the automatic install it will fail. Ill write a configuration script for debian jessie later on tonight when i get off work :)

**Comment by ImmRanneft** [comment]
@mbround18 okay - gonna try to install it manually in this case - thank you!

**Comment by mbround18** [comment]
@ImmRanneft the readme has a missed step when you get to the install ruby portion use the following: 
```sh
# Install Ruby
cd ~
source .bashrc
echo 'eval "$(rbenv init -)"' >> .bashrc
source .bashrc
rbenv install 2.3.1 # Recommended Version as this is the version the source is based on 
rbenv shell 2.3.1 # Change the version number here if you are not using the recommended version
rbenv local 2.3.1
rbenv global 2.3.1
```
the above is updated on my local but I havent had time to do a release due to moving

**Comment by ImmRanneft** [comment]
@mbround18 again thanks, but rbenv failed to build ruby for me cause related openssl issue. Obviously it is not your fault. Looking for solution :)
rbenv suggests to install libssl-dev, while apt says I already have latest.

**Comment by ImmRanneft** [comment]
@mbround18 regarding to https://github.com/rbenv/ruby-build/issues/1006 I was able to compile ruby 2.4.0 with default debian 8.7 jessie.

Also I was able to install ark-manager-web, build bundles and so on (just after changin ruby version to 2.4.0 in Gemfile), so I tend to think you can easily bump ruby version to 2.4.0 after I'll report you that everything goes smoothly.

**Comment by mbround18** [comment]
@ImmRanneft I am still doing a risk assessment on the jump from 2.3.x to 2.4.x and thats intended to be in the 1.1.0 release of this toolkit

**Comment by mbround18** [comment]
@ImmRanneft bumped ruby version to 2.4.1 and updated dependencies ill have to try a build to see if its packager complient

**Comment by mbround18** [comment]
@ImmRanneft I might have to sunset packager.io support because they only support up to 2.3.1 currently
