### ISSUE TITLE
Missing requirements causes ark-manager to flood the stderror log

### ISSUE THREAD

**Issue by ImmRanneft** [mbround18/ark-manager-web#11]
I.e. if you don't have arkamanger then you gonna have really big log file until you will kill the unicorn process.

**Comment by mbround18** [comment]
Ill add a catch for not having that installed however in the readme there is install instructions for arkmanager that occurs before you start the web interface

**Comment by ImmRanneft** [comment]
Sure, but master process isn't stop after error and it continue to write log with 50 lines per second and also it adds little mess when you are pretty sure that process failed to start and you are trying to start it again and it fails cause address is already binded (sorry for tongue tied sentence)

**Comment by mbround18** [comment]
Ill add a stop function so that way it doesnt spam console and will crash if dependencies are not present

**Comment by mbround18** [comment]
I have a potential fix for this that im testing currently
