### ISSUE TITLE
Get Player List onto a panel

### ISSUE THREAD

**Issue by mbround18** [mbround18/ark-manager-web#5]
Convert playerlist using the following command and build a panel for player info.

arkmanager rconcmd listplayers | sed '2d; $d; s/^ *//'

**Comment by mbround18** [comment]
For this enhancement to become a real thing I would need several people to come play for 15 minutes on my servers in unison.

**Comment by thakyZ** [comment]
@mbround18 what's your server's IP? And are there any mods?

**Comment by mbround18** [comment]
my servers are at [GamerDropZone](https://boop.ninja) which do you prefer rag or se?

**Comment by mbround18** [comment]
Well @thakyZ its not pretty but I worked through it with a buddy and got the feature in :)
